on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build and restore dependencies
        run: |
          dotnet build TechnitiumLibrary/TechnitiumLibrary/TechnitiumLibrary.csproj -c Release
          dotnet build TechnitiumLibrary/TechnitiumLibrary.Net/TechnitiumLibrary.Net.csproj -c Release
          dotnet restore ProxmoxAutodiscoveryApp/ProxmoxAutodiscoveryApp.csproj

      - name: Build ProxmoxAutodiscoveryApp
        run: |
          TEST_APP_VERSION=${{ github.ref_name }}
          APP_VERSION=0.0.1

          echo APP_VERSION=${APP_VERSION:1}

          dotnet publish ProxmoxAutodiscoveryApp/ProxmoxAutodiscoveryApp.csproj --no-restore --configuration Release --output release -p:Version=${APP_VERSION:1}

      - name: Create artifact archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: release.zip
          directory: release
          exclusions: DnsServerCore*

      - uses: actions/upload-artifact@v4
        with:
          name: release-archive
          path: release.zip
