on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-tags: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Build and restore dependencies
        run: |
          dotnet build TechnitiumLibrary/TechnitiumLibrary/TechnitiumLibrary.csproj -c Release
          dotnet build TechnitiumLibrary/TechnitiumLibrary.Net/TechnitiumLibrary.Net.csproj -c Release
          dotnet restore ProxmoxAutodiscoveryApp/ProxmoxAutodiscoveryApp.csproj

      - name: Build ProxmoxAutodiscoveryApp
        run: |
          APP_VERSION=${{ github.ref_name }}

          echo APP_VERSION=${APP_VERSION:1}

          dotnet publish ProxmoxAutodiscoveryApp/ProxmoxAutodiscoveryApp.csproj --no-restore --configuration Release --output release -p:Version=${APP_VERSION:1}

      - name: Create artifact archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: ProxmoxAutodiscoveryApp-${{ github.ref_name }}.zip
          directory: release
          exclusions: DnsServerCore*

      - name: Detect previous tag
        run: echo "PREVIOUS_TAG=$(git tag -l --sort=-v:refname | head -n 2 | tail -n 1)" | tee -a $GITHUB_ENV

      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: release/ProxmoxAutodiscoveryApp-${{ github.ref_name }}.zip
          draft: true
          generateReleaseNotes: true
          generateReleaseNotesPreviousTag: ${{ env.PREVIOUS_TAG }}
